# Generated by Django 4.0.4 on 2022-05-01 06:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000)])),
                ('numbers', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('create_date', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('company', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ProductNumberOne',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.baseproduct')),
                ('something_extra', models.CharField(blank=True, max_length=225, null=True)),
            ],
            bases=('Product.baseproduct',),
        ),
        migrations.CreateModel(
            name='ProductNumberThree',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.baseproduct')),
                ('something_extra', models.CharField(blank=True, max_length=225, null=True)),
            ],
            bases=('Product.baseproduct',),
        ),
        migrations.CreateModel(
            name='ProductNumberTwo',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.baseproduct')),
                ('something_extra', models.CharField(blank=True, max_length=225, null=True)),
            ],
            bases=('Product.baseproduct',),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_brand', to='Product.brand'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category', to='Product.category'),
        ),
    ]
